// <auto-generated />
namespace it_project.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class changeEmailDisplay : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(changeEmailDisplay));
        
        string IMigrationMetadata.Id
        {
            get { return "202102041648442_changeEmailDisplay"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
